[[redirects]]
  from="/api/*"
  to="https://final-food-be-production.up.railway.app/api/:splat"
  status=200
  force=true # COMMENT: ensure that we always redirect
  headers={X-From = "Netlify"}
[[redirects]]
  from="/*"
  to="/"
  status=200