[[redirects]]
  from="/api/*"
  to="https://final-food-be-production.up.railway.app/:splat"
  status=200
  force=true # COMMENT: ensure that we always redirect
  headers={X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200